language: bash
services: docker

env:
  - RT_TEST_PARALLEL=1

# $TRAVIS_BUILD_DIR will have a clone of the current branch
before_install:
  - docker build -t rt-base .
  - docker run -d -v $TRAVIS_BUILD_DIR:/rt --name rt rt-base
  - docker ps -a
  - docker exec -it rt bash -c "cd /rt && ./configure.ac --with-db-type=SQLite --with-my-user-group --enable-layout=inplace --enable-developer --enable-externalauth --disable-gpg --disable-smime && mkdir -p /rt/var && make testdeps"

script:
    - docker exec -it rt bash -c "cd /rt && prove -lj9 t/*"
